### PR TITLE
Delete guide/images/architecture/c4.component-gdc.png

### PR DESCRIPTION
**Pull request by tomkralidis**
Moved to https://github.com/wmo-im/wis2-gdc/blob/main/docs/architecture/c4.container.png (no impact to Guide content).

### CODE REVIEW

**Comment by golfvert** [comment]
The GDC Metrics Collector is not, for me, connected to the GDC Broker. However, it is scraped by the Global Monitor. So, there should be an additional box on the top with the Global Cache and Global Broker.

**Comment by antje-s** [comment]
Proposed updates:
- GM connectes to OpenMetrics-URL offered via GDC API
- GB subscribes to GDC Broker
- GC subscribes to GB and downloads data via GDC API URL
- GDC Management subscribes to GB to receive notifications for metadata and download metadata files via GC download URL
Would it then be a complete picture?

**Comment by tomkralidis** [comment]
Thanks @golfvert / @antje-s.  I've updated the diagram in https://github.com/wmo-im/wis2-gdc/blob/main/docs/architecture/c4.container.png accordingly.

Note that this PR deletes this diagram from this repository in lieu of moving it to the wis2-gdc RI repository (the idea being that detailed component diagrams can go into the GitHub repositories of RI themselves).

**Review by golfvert — APPROVED** [review]
OK

**Pull request merged**
